### ISSUE TITLE
Ensure output files from `style-dictionary` and `build-tokens` contain "Do not edit" messaging

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/paragon#1969]
By default, `style-dictionary` appears to include a file header at the top of its automatically generated output files to indicate to contributors that those output files are not intended to be manually edited.

Example:

```css
// Do not edit directly
// Generated on Fri, 27 Jan 2023 16:54:59 GMT

:root {
  --pgn-color-primary-base: #FF0000FF;
}
```

Consider creating a custom file header with more details as well.

Without the file header, we run the risk of contributors wanting to manually edit the output files instead of editing the underlying design tokens instead.

The below config option may be related:

```js
options: {
  showFileHeader: false,
},
```
