### ISSUE TITLE
Regression in floating labels

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/paragon#3514]
Discovered in the `authn` MFE https://github.com/openedx/frontend-app-authn/issues/1467

Narrowed down to https://github.com/openedx/paragon/pull/3451

~Will update with more info shortly~

I wasn't able to reproduce this on a sandbox, I tried using
```jsx
<Form.Group>
  <Form.Control
    floatingLabel="Float"
    value={''}
    autoComplete="on"
  />
</Form.Group>
```

but no dice.

When inspecting the floating label (when it's floating) on the sandbox I saw

![Image](https://github.com/user-attachments/assets/e0cc85b5-bfd1-4dbe-9a61-b25d8aad88e3)

And on `frontend-app-authn` I saw

![Image](https://github.com/user-attachments/assets/2dd4a0b2-811f-4345-9823-d27316e7878b)

The thing that stood out to me the most is the missing `background-color: #fff;` on `frontend-app-authn`, but I'm still not quite sure why that's the case.

I checked https://authn.edx.org/login but the styles there appear to not have the changes yet, when inspecting I saw
```scss
  .form-control:focus ~ &,
  // select.form-control ~ &,
  .form-control.has-value ~ & {
    .pgn__form-control-floating-label-text {
      background-color: $input-bg;
    }

    @include form-control-floating-label-float(
      $input-padding-x,
      $input-padding-y,
      $input-line-height,
      $input-font-size,
      $input-border-width
    );
  }
```

The issue *does* appear on https://authn.stage.edx.org/login
